source 'https://rubygems.org'

gem 'airrecord'
gem 'nokogiri'
gem 'faraday'
gem 'goodreads'
gem 'pinboard'
gem 'faraday_middleware'
gem 'hashdiff'
gem 'dotenv'
gem 'rollbar'
gem 'oxford_dictionary'
gem 'stemmify'

gem 'pry-byebug'
gem 'rake'
